---
title: "People Analytics - Excercice 1"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Question 1 : Tactic A versus Tactic B
**Answer :**

The average performance change for each tactic and th control group is the following
**Control group :** +1%
**Tactic A :** -8%
**Tactic B :** +5%



The standard deviation is relatively similar for each group going from 100% to 102%. Therefore, we can conclude that, in average, the Tactic A decrease employee's performance while Tact B improves it. Unfortunately, I don't know why the "Expert" says that Tactic A helps employes while Tactic B arm them. 



## Question 2 : Google

**Experiment Design for number of interviews at Google**


NR  O1 X1 O2 X2 O3 X3 ... On Xn
NR  O1 X1 O2 X2 O3 X3 ... On Xn
...
NRn O1 X1 O2 X2 O3 X3 ... On Xn

The researcher look at the data post-interview to find after how many interview there's diminishing returns. So they observice the score, than there's another interview, than observe the score again, etc. Until they find the optimal number of interview. They did this for all the candidate so each candidate was an experiment by itself.

**Threats :** 
1. There's certainly variance in the results since some candidate would require less than 4 interview while other might require more. Fixing the number of interview to four might, in average, be beneficial but other candidate would have benefited from having less of more interviews.
2. They have looking at the data after the fact. There's wasn't a experimental process in place. They could have done cohorts of candidate and administered a different number of interview per cohort. They could have eveluated, for each cohort, the number of candidate hired, the number of candidate that drop and the performance after they started. This would be a more scientificly proven way of evaluating the optima number of interview
3. The data they used have many variable such as the interviewers, the time of the day, the back ground of the candidate, the level of the role, etc. It's certainly a challenge to isolate the number of interview of the other variables.

